#!/usr/bin/env bash

echo -e "Updating package repository...\n"

sudo apt-get update -y -qq

function install() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        sudo apt-get install -y "$1" -qq || { echo "Error: Failed to install $1. Exiting."; exit 1; }
    fi
}

install haproxy

echo -e "Setting up some minor stuff...\n"

sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 422943-web-01 34.201.174.220  check
    server 422943-web-02 54.237.33.18 check
"

echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg || { echo "Error: Failed to write HAProxy configuration. Exiting."; exit 1; }

echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy || { echo "Error: Failed to enable HAProxy. Exiting."; exit 1; }

echo "Configured - Roundrobin On web-01 & web-02"

if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start || { echo "Error: Failed to start HAProxy. Exiting."; exit 1; }
else
    sudo service haproxy restart || { echo "Error: Failed to restart HAProxy. Exiting."; exit 1; }
fi

echo "HAProxy installation and configuration completed successfully."